/** Local read-only compatibility witness against unchanged site193; zero live transport. */
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import bridge from '../../../portfolio-next09/lib/notifications/bridge';
import http from '../../../portfolio-next09/lib/notifications/http';
import worker from '../../../portfolio-next09/lib/notifications/worker';
import {signConnection} from '../../server/platform-connection';
const site=new URL('../../../portfolio-next09/',import.meta.url);
assert.equal(execFileSync('git',['rev-parse','HEAD'],{cwd:site,encoding:'utf8'}).trim(),'712ff1c2d9ff95419c0cd1fab91a91901b509835');
const uuid='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',cohort='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const secret='synthetic-bridge-secret-not-real-32-bytes',body='synthetic-body',time=String(Date.now());
assert.equal(signConnection(secret,time,body),bridge.bridgeSignature(secret,time,body));
assert.equal(bridge.verifyBridge(secret,time,signConnection(secret,time,body),body),true);
assert.equal(bridge.verifyBridge(secret,time,signConnection(secret,time,body),body+'altered'),false);
console.log('PASS 1: mini5 bridge matches site193 signature; altered body refused.');
const path=`/publications/${uuid}?cohort=${cohort}`;
assert.equal(new URL(bridge.publicationLink('https://synthetic.invalid',path)).searchParams.get('next'),path);
for(const invalid of [path+'&cohort='+cohort,path+'#fragment','//foreign.invalid',path+'&user_id=other'])assert.throws(()=>bridge.publicationLink('https://synthetic.invalid',invalid));
console.log('PASS 2: exact version/cohort return path retained; malformed and foreign targets refused. Scope authorization remains canonical.');
const calls:{name:string;args:unknown}[]=[];
const gateway={authenticate:async()=>({user:{id:'synthetic-site-A'},error:null}),rpc:async(name:string,args:unknown)=>{calls.push({name,args});return {data:{ok:true},error:null};}};
const post=(value:unknown)=>new Request('https://synthetic.invalid/api/notifications',{method:'POST',headers:{origin:'https://synthetic.invalid'},body:JSON.stringify(value)});
assert.equal((await http.memberNotifications(post({action:'preferences',course:false,updates:true}),async()=>gateway,true)).status,200);
assert.deepEqual(calls.pop(),{name:'next09_preferences',args:{p_course:false,p_updates:true}});
assert.equal((await http.memberNotifications(post({action:'unlink'}),async()=>gateway,true)).status,200);
assert.deepEqual(calls.pop(),{name:'next09_unlink',args:{}});
assert.equal((await http.memberNotifications(post({action:'preferences',course:true,updates:true,user_id:'foreign'}),async()=>gateway,true)).status,422);
assert.equal(calls.length,0);
console.log('PASS 3: explicit independent notification categories and owner-session unlink use existing RPCs; forged owner refused.');
for(const [error,status] of [[{status:401},401],[{status:503},503]] as const){
 const response=await http.memberNotifications(post({action:'unlink'}),async()=>({...gateway,authenticate:async()=>({user:null,error})}),true);
 assert.equal(response.status,status);assert.match(response.headers.get('cache-control')!,/no-store/);
}
assert.equal(calls.length,0);console.log('PASS 4: Auth reject/outage separated, no private RPC on failed Auth.');
let sent=0,finished:Record<string,unknown>|undefined;
const job={attemptId:uuid,telegramId:'100001',kind:'published' as const,version:2,sitePath:path};
await worker.runDistribution({rpc:async(name:string,args?:Record<string,unknown>)=>{if(name==='next09_finish')finished=args;return {error:null,data:name==='next09_claim'?job:name==='next09_check_attempt'?false:{}};}},async()=>{sent++;return {status:'accepted',code:'ok'};},1);
assert.equal(sent,0);assert.equal(finished?.p_status,'cancelled');
console.log('PASS 5: changed/unlinked/revoked authorization mock cancels before transport. No SQL/native binding accepted.');
let captured='';
const delivery=await worker.telegramDelivery('synthetic-token',job,'https://synthetic.invalid',async(_url:unknown,init:RequestInit)=>{captured=String(init.body);return Response.json({ok:true,result:{message_id:7}});});
assert.equal(delivery.status,'accepted');const envelope=JSON.parse(captured);
assert.equal(new URL(envelope.reply_markup.inline_keyboard[0][0].url).searchParams.get('next'),path);
assert.equal(envelope.parse_mode,undefined);assert.equal(envelope.link_preview_options.is_disabled,true);assert.equal('readAt' in delivery,false);
console.log('PASS 6: injected fake transport has generic message and scoped link; API-accepted is not read/transaction. No real fetch.');
const sql=readFileSync(new URL('supabase/migrations/20261001125428_next09_notifications.sql',site),'utf8');
const confirm=sql.slice(sql.indexOf('CREATE FUNCTION public.next09_confirm_link'),sql.indexOf('CREATE FUNCTION public.next09_unlink'));
const unlink=sql.slice(sql.indexOf('CREATE FUNCTION public.next09_unlink'),sql.indexOf('CREATE FUNCTION public.next09_preferences'));
assert.match(confirm,/VALUES\(u,false,false\)/);assert.match(unlink,/VALUES\(u,false,false\)/);
console.log('STATIC: existing confirm/unlink resets categories to false; link/preference epochs rechecked by valid_job. SQL not executed in this witness.');
