import {describe,test,expect,vi,afterEach} from 'vitest';
import {provePlatformConnection,signConnection,privateConnectionUpdate} from './platform-connection';
import {copyLeadToPlatform} from './leadWebhook';
import {leadReference} from './lead-correlation';
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();vi.restoreAllMocks();});
describe('NEXT09 verified connection and correlated copy',()=>{
 test('legacy receipts cannot be blindly copied again under a new reference',()=>{vi.stubEnv('NEXT09_LEAD_NAMESPACE','sandbox-01');vi.stubEnv('NEXT09_LEAD_FIRST_RECEIPT_ID','10');expect(()=>leadReference(9)).toThrow();expect(leadReference(10)).toBe('sandbox-01:10');vi.stubEnv('NEXT09_LEAD_FIRST_RECEIPT_ID','');expect(()=>leadReference(10)).toThrow();});
 test('disabled bridge does not make network calls; only private same-user update qualifies',async()=>{const f=vi.fn();await expect(provePlatformConnection('a'.repeat(64),'100001',f)).rejects.toThrow();expect(f).not.toHaveBeenCalled();expect(privateConnectionUpdate({from:{id:100001},chat:{id:100001,type:'private'}})).toBe(true);expect(privateConnectionUpdate({from:{id:100001},chat:{id:100002,type:'private'}})).toBe(false);expect(privateConnectionUpdate({from:{id:100001},chat:{id:100001,type:'group'}})).toBe(false);});
 test('signed bridge has fixed origin, binds verified id and returns only final-site proof',async()=>{vi.stubEnv('NEXT09_ENABLED','true');vi.stubEnv('NEXT09_BRIDGE_SECRET','synthetic-bridge-secret-at-least-32');vi.stubEnv('NEXT09_PLATFORM_ORIGIN','https://example.invalid');let body='',headers:Record<string,string>={};const f=vi.fn(async(_u,init)=>{body=String(init.body);headers=init.headers;return Response.json({contractVersion:'notifications.v1',confirmation:'f'.repeat(64)});});const r=await provePlatformConnection('a'.repeat(64),'100001',f);expect(r.status).toBe('site_confirmation_required');expect(JSON.parse(body).telegramId).toBe('100001');expect(headers['x-next09-signature']).toBe(signConnection(process.env.NEXT09_BRIDGE_SECRET!,headers['x-next09-time'],body));expect(f.mock.calls[0][1].redirect).toBe('error');});
 test('correlation preserves same receipt across bounded retry and redacts rejected response/network detail',async()=>{vi.stubEnv('PLATFORM_WEBHOOK_SECRET','synthetic-secret');vi.stubEnv('PLATFORM_WEBHOOK_URL','https://example.invalid');const payload={source:'miniapp',external_ref:'sandbox-01:10',name:'Synthetic',phone:'00000000000',topic:'other',message:null,preferred_date:null,preferred_time:null,telegram_username:null,telegram_id:'100001'};const f=vi.fn().mockResolvedValueOnce(Response.json({error:'private-contact'},{status:503})).mockRejectedValueOnce(new Error('secret-network-detail')).mockResolvedValueOnce(Response.json({ok:true}));vi.stubGlobal('fetch',f);const spy=vi.spyOn(console,'error').mockImplementation(()=>{});expect((await copyLeadToPlatform(payload)).ok).toBe(true);expect(f).toHaveBeenCalledTimes(3);expect(f.mock.calls.map(x=>JSON.parse(x[1].body).external_ref)).toEqual(['sandbox-01:10','sandbox-01:10','sandbox-01:10']);expect(JSON.stringify(spy.mock.calls)).not.toContain('private-contact');});
});
